include: opopops/python/apko/shell.yaml

contents:
  packages:
    - apk-tools
    - build-base
    - git
    - py3-pip
    - uv

accounts:
  run-as: root

work-dir: /

entrypoint:
  command: ""

cmd: /bin/sh -l
