include: apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - socat
    - wolfi-baselayout

entrypoint:
  command: /usr/bin/socat

annotations:
  org.opencontainers.image.title: 'socat'
  org.opencontainers.image.description: 'Socat image based on Wolfi OS'
