include: apko.yaml

contents:
  packages:
    - alpine-keys
    - bash
    - bubblewrap
    - busybox
    - ca-certificates-bundle
    - glibc
    - glibc-locale-posix
    - ld-linux
    - libcap
    - libgcc
    - melange
    - wolfi-baselayout
    - wolfi-keys

entrypoint:
  command: /usr/bin/melange

cmd: --help

annotations:
  org.opencontainers.image.title: 'melange'
  org.opencontainers.image.description: 'Melange image based on Wolfi OS'