include: ../../apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - curl
    - jq
    - tzdata
    - unzip
    - wolfi-baselayout
    - yq

entrypoint:
  command: bash -c
