include: apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - curl
    - jq
    - openssl
    - tree
    - tzdata
    - unzip
    - vim
    - wolfi-baselayout
    - yq

cmd: /bin/sh -l
