include: apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - curl
    - jq
    - openssl
    - tree
    - tzdata
    - unzip
    - vim
    - wolfi-baselayout
    - yq

cmd: /bin/sh -l

annotations:
  org.opencontainers.image.title: 'shell'
  org.opencontainers.image.description: 'Shell image based on Wolfi OS'