include: opopops/shell/apko/base.yaml

contents:
  packages:
    - apk-tools
    - build-base
    - git
    - wolfi-base

accounts:
  run-as: root

work-dir: /

entrypoint:
  command: ""

cmd: /bin/sh -l
