contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - https://packages.cgr.dev/extras
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - curl
    - helm
    - jq
    - kubectl
    - nano
    - tree
    - tzdata
    - unzip
    - vim
    - wolfi-baselayout
    - wolfi-keys
    - yq

annotations:
  image-author: opopops
  image-source: https://github.com/opopops/docker/opopops

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: nonroot

work-dir: /home/nonroot

entrypoint:
  command: bash -c

archs:
  - x86_64
  - arm64
