include: ../../apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - cosign
    - curl
    - grype
    - helm
    - jq
    - k9s
    - kubectl
    - tzdata
    - unzip
    - wolfi-baselayout
    - yq

cmd: /bin/sh -l
