name: grype-scan
description: "Scan a container image."

inputs:
  image:
    description: "The image to scan."
    required: true
  scan-fail-build:
    description: "Whether to fail the build if vulnerabilities are found."
    required: false
    default: "false"
  scan-severity-cutoff:
    description: "The severity of vulnerabilities that should cause the scan to fail."
    required: false
    default: "high"

runs:
  using: "composite"
  steps:
    - uses: anchore/scan-action@v6
      id: scan
      with:
        image: ${{ inputs.image }}
        cache-db: true
        fail-build: ${{ inputs.scan-fail-build }}
        severity-cutoff: ${{ inputs.scan-severity-cutoff }}

    - uses: github/codeql-action/upload-sarif@v3
      id: scan-report
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
