include: apko.yaml

contents:
  packages:
    - alpine-keys
    - apko
    - bash
    - busybox
    - ca-certificates-bundle
    - glibc-locale-posix
    - wolfi-baselayout
    - wolfi-keys

entrypoint:
  command: /usr/bin/apko

cmd: --help

annotations:
  org.opencontainers.image.title: 'apko'
  org.opencontainers.image.description: 'Apko image based on Wolfi OS'
