include: apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - glibc-locale-posix
    - helm
    - kubectl
    - wolfi-baselayout

entrypoint:
  command: /usr/bin/helm

cmd: --help

annotations:
  org.opencontainers.image.title: 'helm'
  org.opencontainers.image.description: 'Helm image based on Wolfi OS'