name: cosign-sign-and-attest
description: "Publish an APKO container image."

inputs:
  registry:
    description: "The container registry."
    required: false
    default: "ghcr.io"
  image:
    description: "The image name."
    required: true
  tag:
    description: "The image tag."
    required: true
  sbom-path:
    description: "The path to the SBOM directory."
    required: false
    default: ${{ github.workspace }}/sbom

runs:
  using: "composite"
  steps:
    - uses: imjasonh/setup-crane@v0.4
    - uses: sigstore/cosign-installer@v3

    - id: crane
      shell: bash
      run: |
        echo "digest=$(crane digest ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }})" >> $GITHUB_OUTPUT
        echo "digest-amd64=$(crane digest ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }} --platform=linux/amd64)" >> $GITHUB_OUTPUT
        echo "digest-arm64=$(crane digest ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }} --platform=linux/arm64)" >> $GITHUB_OUTPUT

    - id: sign
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign sign \
          --recursive \
          --oidc-provider=github-actions \
          ${{ inputs.registry }}/${{ inputs.image }}@${{ steps.crane.outputs.digest }}

    - uses: actions/attest-build-provenance@v2
      id: attest-provenance
      with:
        subject-name: ${{ inputs.registry }}/${{ inputs.image }}
        subject-digest: ${{ steps.crane.outputs.digest }}
        push-to-registry: true

    - id: attest-index
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-index.spdx.json \
          --oidc-provider=github-actions \
          ${{ inputs.registry }}/${{ inputs.image }}@${{ steps.crane.outputs.digest }}

    - id: attest-amd64
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-x86_64.spdx.json \
          --oidc-provider=github-actions \
          ${{ inputs.registry }}/${{ inputs.image }}@${{ steps.crane.outputs.digest-amd64 }}

    - id: attest-arm64
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-aarch64.spdx.json \
          --oidc-provider=github-actions \
          ${{ inputs.registry }}/${{ inputs.image }}@${{ steps.crane.outputs.digest-arm64 }}
