include: ../../apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - openvpn
    - wolfi-baselayout
    - wolfi-keys

accounts:
  run-as: root

work-dir: /

entrypoint:
  type: service-bundle
  services:
    openvpn: openvpn --config /etc/openvpn/client.conf

stop-signal: SIGQUIT
