name: apko-publish
description: "Publish an APKO container image."

inputs:
  config:
    description: "Path to the APKO configuration file."
    required: true
  image:
    description: "The image name to publish."
    required: true
  tag:
    description: "The image tag to publish."
    required: true
  archs:
    description: "The architectures to build the container image for."
    required: false
    default: "x86_64,aarch64"

outputs:
  digest:
    description: "The digest of the published container image."
    value: ${{ steps.crane.outputs.digest }}
  ref:
    value: ${{ steps.apko.outputs.digest }}
    description: "The full qualified digest of the published container image."
  sbom-path:
    description: "The path to the SBOM index file."
    value: ${{ steps.output.outputs.sbom-path }}

runs:
  using: "composite"
  steps:
    - name: Create outputs
      id: output
      shell: bash
      run: |
        echo "sbom-path=$(mktemp -d -p /tmp -t apko.XXXXXX)" >> $GITHUB_OUTPUT

    - uses: imjasonh/setup-crane@v0.4

    - uses: distroless/actions/apko-publish@main
      id: apko
      with:
        config: ${{ inputs.config }}
        tag: ghcr.io/${{ inputs.image }}:${{ inputs.tag }}
        archs: ${{ inputs.archs }}
        sbom-path: ${{ steps.output.outputs.sbom-path }}

    - id: crane
      shell: bash
      run: |
        crane cp ${{ steps.apko.outputs.digest }} docker.io/${{ inputs.image }}:${{ inputs.tag }}
        echo "digest=$(crane digest ghcr.io//${{ inputs.image }}:${{ inputs.tag }})" >> $GITHUB_OUTPUT
