name: apko

on:
  push:
    branches:
      - "main"
    paths:
      - "opopops/apko/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        include:
          - tag: latest
            target: base
            packages: ''
    name: ${{ matrix.tag }}
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      tag: ${{ matrix.tag }}
      target: ${{ matrix.target }}
      packages: ${{ matrix.packages }}
    secrets: inherit
