name: code-server

on:
  push:
    branches:
      - "main"
    paths:
      - "opopops/code-server/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  latest:
    if: github.ref_name == 'main'
    name: latest
    uses: "./.github/workflows/workflow-docker.yml"
    with:
      tag: latest
      scan: "false"
      sign: "false"
    secrets: inherit

  unstable:
    if: github.ref_name == 'dev'
    name: unstable
    uses: "./.github/workflows/workflow-docker.yml"
    with:
      tag: unstable
      scan: "false"
      sign: "false"
    secrets: inherit
