name: code-server

on:
  schedule:
    - cron: "00 01 * * 1"
  push:
    branches:
      - 'main'
    paths:
      - 'images/code-server/Dockerfile'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        arch: [amd64, arm64]
        variant: [prod]
        version: [latest]
        include:
          - version: latest
    name: ${{ matrix.version }}-${{ matrix.arch }}${{ matrix.variant == 'dev' && '-dev' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      platforms: linux/${{ matrix.arch }}
      target: ${{ matrix.variant }}
      tag: ${{ matrix.version }}-${{ matrix.arch }}${{ matrix.variant == 'dev' && '-dev' || '' }}
      scan: 'false'
    secrets: inherit
