name: crane

on:
  push:
    branches:
      - "main"
    paths:
      - "opopops/crane/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  latest:
    if: github.ref_name == 'main'
    name: latest
    environment: main
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: ./.github/actions/apko
        with:
          config: opopops/crane/apko/base.yaml
          tag: opopops/crane:latest
          dockerhub-username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          cosign-password: ${{ secrets.COSIGN_PASSWORD }}
          cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
          cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}

  unstable:
    if: github.ref_name == 'dev'
    name: unstable
    environment: main
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: ./.github/actions/apko
        with:
          config: opopops/crane/apko/base.yaml
          tag: opopops/crane:unstable
          dockerhub-username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          cosign-password: ${{ secrets.COSIGN_PASSWORD }}
          cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
          cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
