name: iac

on:
  push:
    branches:
      - "main"
    paths:
      - "opopops/iac/**"
  workflow_dispatch:

jobs:
  latest:
    if: github.ref_name == 'main'
    name: latest
    uses: "./.github/workflows/.release-docker.yml"
    with:
      scan: false
    secrets: inherit
