name: iac

on:
  push:
    branches:
      - "main"
    paths:
      - "opopops/iac/**"
  workflow_dispatch:

jobs:
  latest:
    if: github.ref_name == 'main'
    name: latest
    uses: "./.github/workflows/.docker.yml"
    with:
      scan: false
    secrets: inherit

  unstable:
    if: github.ref_name == 'dev'
    name: unstable
    uses: "./.github/workflows/.docker.yml"
    with:
      runner: self-hosted
      scan: false
    secrets: inherit
