name: k8s

on:
  push:
    branches:
      - "main"
    paths:
      - "opopops/k8s/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  latest:
    if: github.ref_name == 'main'
    name: latest
    environment: main
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: ./.github/actions/docker
        with:
          context: opopops/k8s
          file: opopops/k8s/Dockerfile
          tag: opopops/k8s:latest
          dockerhub-username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          scan: "false"
          cosign: "false"

  unstable:
    if: github.ref_name == 'dev'
    name: unstable
    environment: main
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: ./.github/actions/docker
        with:
          context: opopops/k8s
          file: opopops/k8s/Dockerfile
          tag: opopops/k8s:unstable
          dockerhub-username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          scan: "false"
          cosign: "false"
