name: k8s

on:
  push:
    branches:
      - "main"
    paths:
      - "opopops/k8s/**"
  workflow_dispatch:

jobs:
  latest:
    if: github.ref_name == 'main'
    name: latest
    uses: ./.github/actions/docker
    with:
      scan: false
    secrets: inherit

  unstable:
    if: github.ref_name == 'dev'
    name: unstable
    uses: ./.github/actions/docker
    with:
      runner: self-hosted
      scan: false
    secrets: inherit
