name: melange

on:
  push:
    branches:
      - "main"
    paths:
      - "opopops/melange/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  latest:
    if: github.ref_name == 'main'
    name: latest
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      tag: latest
    secrets: inherit

  unstable:
    if: github.ref_name == 'dev'
    name: unstable
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      tag: unstable
    secrets: inherit
