name: openvpn

on:
  push:
    branches:
      - "main"
    paths:
      - "opopops/openvpn/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  latest:
    if: github.ref_name == 'main'
    name: latest
    environment: main
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: ./.github/actions/apko
        with:
          config: opopops/openvpn/apko/base.yaml
          tag: opopops/openvpn:latest
          github-token: ${{ secrets.GH_REGISTRY_PASSWORD }}
          registry-username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

  latest-dev:
    if: github.ref_name == 'main'
    name: latest-dev
    environment: main
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: ./.github/actions/apko
        with:
          config: opopops/openvpn/apko/dev.yaml
          tag: opopops/openvpn:latest-dev
          github-token: ${{ secrets.GH_REGISTRY_PASSWORD }}
          registry-username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

  unstable:
    if: github.ref_name == 'dev'
    name: unstable
    environment: main
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: ./.github/actions/apko
        with:
          config: opopops/openvpn/apko/base.yaml
          tag: opopops/openvpn:unstable
          github-token: ${{ secrets.GH_REGISTRY_PASSWORD }}
          registry-username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

  unstable-dev:
    if: github.ref_name == 'dev'
    name: unstable-dev
    environment: main
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: ./.github/actions/apko
        with:
          config: opopops/openvpn/apko/dev.yaml
          tag: opopops/openvpn:unstable-dev
          github-token: ${{ secrets.GH_REGISTRY_PASSWORD }}
          registry-username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
