name: python

on:
  push:
    branches:
      - "main"
      - "dev"
    paths:
      - "opopops/python/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  latest:
    if: github.ref_name == 'main'
    name: latest
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      tag: latest
    secrets: inherit

  latest-shell:
    if: github.ref_name == 'main'
    name: latest-shell
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      target: shell
      tag: latest-shell
    secrets: inherit

  latest-dev:
    if: github.ref_name == 'main'
    name: latest-dev
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      target: dev
      tag: latest-dev
    secrets: inherit

  unstable:
    if: github.ref_name == 'dev'
    name: unstable
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      tag: unstable
    secrets: inherit

  unstable-shell:
    if: github.ref_name == 'dev'
    name: unstable-shell
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      target: shell
      tag: unstable-shell
    secrets: inherit

  unstable-dev:
    if: github.ref_name == 'dev'
    name: unstable-dev
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      target: dev
      tag: unstable-dev
    secrets: inherit
