name: weekly

on:
  schedule:
    - cron: "05 06 * * 1" # 06:05 (UTC) every Monday
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  apko:
    strategy:
      matrix:
        target: [base, shell]
        tag: [latest, latest-shell]
        exclude:
          - target: base
            tag: latest-shell
          - target: shell
    name: apko
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/apko
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit

  crane:
    strategy:
      matrix:
        target: [base, shell]
        tag: [latest, latest-shell]
        exclude:
          - target: base
            tag: latest-shell
          - target: shell
    name: crane
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/crane
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit

  grype:
    strategy:
      matrix:
        target: [base, shell]
        tag: [latest, latest-shell]
        exclude:
          - target: base
            tag: latest-shell
          - target: shell
    name: grype
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/grype
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit

  helm:
    strategy:
      matrix:
        target: [base, shell]
        tag: [latest, latest-shell]
        exclude:
          - target: base
            tag: latest-shell
          - target: shell
    name: helm
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/helm
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit

  kshell:
    strategy:
      matrix:
        target: [base, dev]
        tag: [latest, latest-dev]
        exclude:
          - target: base
            tag: latest-dev
          - target: dev
            tag: latest
    name: kshell
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/kshell
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit

  melange:
    strategy:
      matrix:
        target: [base, shell]
        tag: [latest, latest-shell]
        exclude:
          - target: base
            tag: latest-shell
          - target: shell
    name: melange
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/melange
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit

  openvpn:
    strategy:
      matrix:
        target: [base, shell]
        tag: [latest, latest-shell]
        exclude:
          - target: base
            tag: latest-shell
          - target: shell
            tag: latest
    name: openvpn
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/openvpn
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit

  prometheus-node-exporter:
    strategy:
      matrix:
        target: [base, shell]
        tag: [latest, latest-shell]
        exclude:
          - target: base
            tag: latest-shell
          - target: shell
            tag: latest
    name: prometheus-node-exporter
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/prometheus-node-exporter
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit

  python:
    strategy:
      matrix:
        target: [base, shell, dev]
        tag: [latest, latest-shell, latest-dev]
        exclude:
          - target: base
            tag: latest-shell
          - target: base
            tag: latest-dev
          - target: shell
            tag: latest
          - target: shell
            tag: latest-dev
          - target: dev
            tag: latest
          - target: dev
            tag: latest-shell
    name: python
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/python
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit

  shell:
    strategy:
      matrix:
        target: [base, dev]
        tag: [latest, latest-dev]
        exclude:
          - target: base
            tag: latest-dev
          - target: dev
            tag: latest
    name: shell
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/shell
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit

  traefik:
    strategy:
      matrix:
        target: [base, shell]
        tag: [latest, latest-shell]
        exclude:
          - target: base
            tag: latest-shell
          - target: shell
            tag: latest
    name: traefik
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/traefik
      target: ${{ matrix.target }}
      tag: ${{ matrix.tag }}
    secrets: inherit
