name: weekyly

on:
  schedule:
    - cron: "05 06 * * 1" # 06:05 (UTC) every Monday
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  apko:
    name: apko
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/apko
      tag: latest
    secrets: inherit

  crane:
    name: crane
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/crane
      tag: latest
    secrets: inherit

  grype:
    name: grype
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/grype
      tag: latest
    secrets: inherit

  helm:
    name: helm
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/helm
      tag: latest
    secrets: inherit

  melange:
    name: melange
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/melange
      tag: latest
    secrets: inherit

  openvpn:
    name: openvpn
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/openvpn
      tag: latest
    secrets: inherit

  shell:
    name: shell
    uses: "./.github/workflows/workflow-apko.yml"
    with:
      image: opopops/shell
      tag: latest
    secrets: inherit
