name: Reusable apko workflow

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image name'
        type: string
        required: false
        default: 'opopops/${{ github.workflow }}'
      tag:
        description: 'Docker image tag'
        type: string
        required: false
        default: 'latest'
      target:
        description: 'The target to build'
        type: string
        required: false
        default: 'base'
      packages:
        description: 'Additional packages'
        type: string
        required: false
        default: ''
      scan:
        description: "Whether to scan the container image for vulnerabilities."
        type: string
        required: false
        default: "true"
      sign:
        description: "Whether to sign the container image."
        type: string
        required: false
        default: "true"

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    environment: main
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.publish.outputs.ref }}
      digest: ${{ steps.publish.outputs.digest }}
      sbom-path: ${{ steps.publish.outputs.sbom-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub
        uses: docker/login-action@v3
        id: login-to-github
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        id: login-to-docker-hub
        with:
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Publish
        id: publish
        uses: ./.github/actions/apko
        with:
          config: ${{ inputs.image }}/apko/${{ inputs.target}}.yaml
          image: ${{ inputs.image }}
          tag: ${{ inputs.tag }}
          scan: ${{ inputs.scan }}

      - name: Sign and Attest image
        uses: ./.github/actions/cosign
        with:
          registry: ghcr.io
          image: ${{ inputs.image }}
          tag: ${{ inputs.tag }}

      - name: Sign image and generate attestations on Docker Hub
        uses: ./.github/actions/cosign
        with:
          registry: docker.io
          image: ${{ inputs.image }}
          tag: ${{ inputs.tag }}

  scan:
    environment: main
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub
        uses: docker/login-action@v3
        id: login-to-github
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Scan
        uses: ./.github/actions/grype
        with:
          image: ${{ needs.publish.outputs.ref }}
