name: Reusable docker workflow

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image name'
        type: string
        required: false
        default: 'opopops/${{ github.workflow }}'
      tag:
        description: 'Docker image tag'
        type: string
        required: false
        default: 'latest'
      target:
        description: 'The target to build'
        type: string
        required: false
        default: 'base'
      scan:
        description: "Whether to scan the container image for vulnerabilities."
        type: string
        required: false
        default: "true"
      sign:
        description: "Whether to sign the container image."
        type: string
        required: false
        default: "true"

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  publish:
    environment: main
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: ./.github/actions/docker
        with:
          context: ${{ inputs.image }}
          file: ${{ inputs.image }}//Dockerfile
          tag: ${{ inputs.image }}:${{ inputs.tag }}
          dockerhub-username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          scan: ${{ inputs.scan }}
          sign: ${{ inputs.sign }}
          cosign-password: ${{ secrets.COSIGN_PASSWORD }}
          cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
          cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
